###
// GET/ addresses REST (Getting Auth User Addresses) 

POST  http://meditationv1.improsyazilim.com/public/api/addresses HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjcxMzYwMmUxMGNkOTRmODJiMDY4NWYwMDAyNzYxNTRlZjc3YzVlMGYxODY5Y2ViNzE5M2ViNjM2MjczNmM1NjRlMDU5MTMxODVlZTcyNmYiLCJpYXQiOjE1NzM5ODA0ODQsIm5iZiI6MTU3Mzk4MDQ4NCwiZXhwIjoxNjA1NjAyODg0LCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.MHDtKaBIsAqgSUdVQ2Yf4Wfnm-rOn4MlMxe8m6ZuBx8bYig_gzhU8iAn5Rpavi0dY8XlwaPWnrd-vmoHgcNETXqbqXrwpUrulydkt6UhMfeeE5vpbgZY7GxQKNpSYtuSOmKS4HnmDZsDYsWh2Rz1uXvLjFkc13buSCTKBO08GvyXqLAAPYUJTfrL-u4Z7442VvI94UzTTI8mLvBIQixzm6gUcOCh4KDhm1FazdU0Ywwr7uhGwgqQlcPB46Ti__YebAZqfoss34qD06FyKFPLY8M_S_jOJ93CCl8EmaPgzn_YWh9wvEf8Pt65o3qWu-xPlxYePWcuKXYh1bGSUZGuxp8vv3QYRvwfpgH6Tho950P8ObWkLe4EYdFwtYAiFRmTzXoRK793LbxXUo0SxkKO7fblBssjDO13cCW84lDWBES_LGyBmab7SpecAVV4Noz56Zzopi63NCE53M19AkKebirXuprRXfXUtrVHGOZ8_9zP3pUpoixlPxC2-2V4IuCiz-GJ2QOzHF0qtdITeSfA1LCtShAFPS9K9uMF-2H98B34fyrQCiez3ICIac57aHYK9lfbrMCEeIj4NUNGvWwahmEkI-iHhO0OaME98yXLWIbd7cPQ2bHETKL8c59PwpPaFA9AxL7kKRDIhMjtzzAlFevkQRFeqym0UaHaogpQp_Y

###
//GET/ cities REST (Getting All Cities) 

POST  http://meditationv1.improsyazilim.com/public/api/cities HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjcxMzYwMmUxMGNkOTRmODJiMDY4NWYwMDAyNzYxNTRlZjc3YzVlMGYxODY5Y2ViNzE5M2ViNjM2MjczNmM1NjRlMDU5MTMxODVlZTcyNmYiLCJpYXQiOjE1NzM5ODA0ODQsIm5iZiI6MTU3Mzk4MDQ4NCwiZXhwIjoxNjA1NjAyODg0LCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.MHDtKaBIsAqgSUdVQ2Yf4Wfnm-rOn4MlMxe8m6ZuBx8bYig_gzhU8iAn5Rpavi0dY8XlwaPWnrd-vmoHgcNETXqbqXrwpUrulydkt6UhMfeeE5vpbgZY7GxQKNpSYtuSOmKS4HnmDZsDYsWh2Rz1uXvLjFkc13buSCTKBO08GvyXqLAAPYUJTfrL-u4Z7442VvI94UzTTI8mLvBIQixzm6gUcOCh4KDhm1FazdU0Ywwr7uhGwgqQlcPB46Ti__YebAZqfoss34qD06FyKFPLY8M_S_jOJ93CCl8EmaPgzn_YWh9wvEf8Pt65o3qWu-xPlxYePWcuKXYh1bGSUZGuxp8vv3QYRvwfpgH6Tho950P8ObWkLe4EYdFwtYAiFRmTzXoRK793LbxXUo0SxkKO7fblBssjDO13cCW84lDWBES_LGyBmab7SpecAVV4Noz56Zzopi63NCE53M19AkKebirXuprRXfXUtrVHGOZ8_9zP3pUpoixlPxC2-2V4IuCiz-GJ2QOzHF0qtdITeSfA1LCtShAFPS9K9uMF-2H98B34fyrQCiez3ICIac57aHYK9lfbrMCEeIj4NUNGvWwahmEkI-iHhO0OaME98yXLWIbd7cPQ2bHETKL8c59PwpPaFA9AxL7kKRDIhMjtzzAlFevkQRFeqym0UaHaogpQp_Y

###
// GET/ districts REST (Getting All Districts) 

POST  http://meditationv1.improsyazilim.com/public/api/districts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjcxMzYwMmUxMGNkOTRmODJiMDY4NWYwMDAyNzYxNTRlZjc3YzVlMGYxODY5Y2ViNzE5M2ViNjM2MjczNmM1NjRlMDU5MTMxODVlZTcyNmYiLCJpYXQiOjE1NzM5ODA0ODQsIm5iZiI6MTU3Mzk4MDQ4NCwiZXhwIjoxNjA1NjAyODg0LCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.MHDtKaBIsAqgSUdVQ2Yf4Wfnm-rOn4MlMxe8m6ZuBx8bYig_gzhU8iAn5Rpavi0dY8XlwaPWnrd-vmoHgcNETXqbqXrwpUrulydkt6UhMfeeE5vpbgZY7GxQKNpSYtuSOmKS4HnmDZsDYsWh2Rz1uXvLjFkc13buSCTKBO08GvyXqLAAPYUJTfrL-u4Z7442VvI94UzTTI8mLvBIQixzm6gUcOCh4KDhm1FazdU0Ywwr7uhGwgqQlcPB46Ti__YebAZqfoss34qD06FyKFPLY8M_S_jOJ93CCl8EmaPgzn_YWh9wvEf8Pt65o3qWu-xPlxYePWcuKXYh1bGSUZGuxp8vv3QYRvwfpgH6Tho950P8ObWkLe4EYdFwtYAiFRmTzXoRK793LbxXUo0SxkKO7fblBssjDO13cCW84lDWBES_LGyBmab7SpecAVV4Noz56Zzopi63NCE53M19AkKebirXuprRXfXUtrVHGOZ8_9zP3pUpoixlPxC2-2V4IuCiz-GJ2QOzHF0qtdITeSfA1LCtShAFPS9K9uMF-2H98B34fyrQCiez3ICIac57aHYK9lfbrMCEeIj4NUNGvWwahmEkI-iHhO0OaME98yXLWIbd7cPQ2bHETKL8c59PwpPaFA9AxL7kKRDIhMjtzzAlFevkQRFeqym0UaHaogpQp_Y

