###
// GET/ addresses REST (Getting Auth User Addresses) 

POST  http://meditationv1.improsyazilim.com/public/api/addresses HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjg4YTM5NTdjNTMzM2VjMDU4ZjNhZTE4OWJjYzM1OTdkMmQwOTI0ZjU1NmMyM2RjZmU0ODgyNWU1NzBlNTYyYmMzMmNiZWNlYTliNWYxYTQiLCJpYXQiOjE1NzM1NzI2ODcsIm5iZiI6MTU3MzU3MjY4NywiZXhwIjoxNjA1MTk1MDg3LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.zBtc0NYlNWn6cQAwFEIZtaJEzWX9uESEO7ledjlevwMEp-f3uQZJhge2vgvZSaJ5idjyqTUmJUWruRw97QFdeA4NxuVY2v0NxYtrYmMc9tcwEBCBHW1Sr9ZDHEtMUBz8uIbvKdytBZUVdSWW66QaaXIDacqEPzFlG0_9K_5RYOgPWQUeQodYA6tqLjawoeuEHLRWTgLCNQRQ0qQAAMGMV4nMR0vJ6Mxw4pRoGSOfr30SLlyJXpCDOUbnrKXadkLfW3RoZFX-gKYIzeSpLbUggqZKGsfkMLC83XMCwCP_gOizFn1gxzHoPEn60RvGVRX3EaXYfyx5X53f6wSXHMaPTjUB1zVxwLIZqS9Eb7UETWQCcGnC15-IAJ-9Nymb7EB0mM3060HUL0qNybChPXo-PDcneZtAtXksqm0Mr77rcceuuULbY8LSWreBf6Mlge1v6suRiKBfE8p05cZ85i3glPE-rEjrnVwP-zdGT665DQNY95YVjY5S8ZOxqEpnaoRAPLtY7oSTmjqHPVWKVkerTiSZapR1FC1ai1mI1ej7btoEsVbhkMOFGeaLLwMfUfR9GkE1q1zn3byU9SDdAf26Fq0Q1i39jcY2vFwYHBKd1euVp3MbzA0cPWvZBg2417nnIR18ywTgohjq3SSWvbTiNxU9OMfUoGLTdtrD0YiE1PI

###
//GET/ cities REST (Getting All Cities) 

POST  http://meditationv1.improsyazilim.com/public/api/cities HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjBjYjkyZTUwY2RjYjA4NDBjMmNjNDMyMzk4ZDVjYzg2MWE5YzBjNDI1MDEwMjE4NDExODFmZjNhY2Y0ZjgyMjhjZjFiZjZiOTI4NTZiNDAiLCJpYXQiOjE1NzM1NzQyNDIsIm5iZiI6MTU3MzU3NDI0MiwiZXhwIjoxNjA1MTk2NjQyLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.lUF4MAuM34nvkxPS4aYr_qxjdwUt38gxbehFfgy6YI5__3cHoTRxkf8NGr1MHDzBa-EDMIw7L6CH-wxGICjXb6T5gZJfxxzzxjvAtAu6aO8-m_ly6GxLhGDa9B8thS7ycLzswftgpkw8k5Azh_2C2d_9RR7hfgNFzfZWPJASGQKStzhfohKuypxq1FcVxru3RVexTbSCB6eYCsoGM8YaEyg1OG9lZ1SmP2mq51dsKVuHKtglEp_MVUfW5vbIakU-glbkRnZLMO7wgPAgjcKuYbw1F0rj2GS5ftsahDvr-m6thjNggd_UNRfQ0fz3ZZYz2rVc8OL_0s38PEpqyAioJHbx8O0nRqQN9TxtUml-iy6BOSymPhBUaqG4KhDKgO5jmLGBG73vYnlhUgaHHGIPUkkQhSU1S0E4pvcY0vdx9plEHW84I7H_tYUk7Db8DSFSjLqeZB-n35WDz2lqkgX99lpfrH9wAHjxOaCiBryX93GmVY4ODk2_QI_uGKEBsvx8bTzMARtSj6rAhBBlG-xPQiK_LJN6NAIonIJNAquFpMdv5By_ltFRtQaDv7Kdf66zuIsH2rUJJ95UGu0SMwwbhmmyZC0arQlBMiStLG6bTp-6NB57uWBrqvTBt8hKU8RhNbLWp0GbH05taH0KbX8rgVyDv5xxMdUVDL4fAzqro7E

###
// GET/ districts REST (Getting All Districts) 

POST  http://meditationv1.improsyazilim.com/public/api/districts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjBjYjkyZTUwY2RjYjA4NDBjMmNjNDMyMzk4ZDVjYzg2MWE5YzBjNDI1MDEwMjE4NDExODFmZjNhY2Y0ZjgyMjhjZjFiZjZiOTI4NTZiNDAiLCJpYXQiOjE1NzM1NzQyNDIsIm5iZiI6MTU3MzU3NDI0MiwiZXhwIjoxNjA1MTk2NjQyLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.lUF4MAuM34nvkxPS4aYr_qxjdwUt38gxbehFfgy6YI5__3cHoTRxkf8NGr1MHDzBa-EDMIw7L6CH-wxGICjXb6T5gZJfxxzzxjvAtAu6aO8-m_ly6GxLhGDa9B8thS7ycLzswftgpkw8k5Azh_2C2d_9RR7hfgNFzfZWPJASGQKStzhfohKuypxq1FcVxru3RVexTbSCB6eYCsoGM8YaEyg1OG9lZ1SmP2mq51dsKVuHKtglEp_MVUfW5vbIakU-glbkRnZLMO7wgPAgjcKuYbw1F0rj2GS5ftsahDvr-m6thjNggd_UNRfQ0fz3ZZYz2rVc8OL_0s38PEpqyAioJHbx8O0nRqQN9TxtUml-iy6BOSymPhBUaqG4KhDKgO5jmLGBG73vYnlhUgaHHGIPUkkQhSU1S0E4pvcY0vdx9plEHW84I7H_tYUk7Db8DSFSjLqeZB-n35WDz2lqkgX99lpfrH9wAHjxOaCiBryX93GmVY4ODk2_QI_uGKEBsvx8bTzMARtSj6rAhBBlG-xPQiK_LJN6NAIonIJNAquFpMdv5By_ltFRtQaDv7Kdf66zuIsH2rUJJ95UGu0SMwwbhmmyZC0arQlBMiStLG6bTp-6NB57uWBrqvTBt8hKU8RhNbLWp0GbH05taH0KbX8rgVyDv5xxMdUVDL4fAzqro7E

