###
//authorProfileInfos REST (Getting Author Profile) 

POST  http://meditationv1.improsyazilim.com/public/api/authorProfileInfos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWFjN2E0ODczYTA3ZTRmZDgyZDE5NmExNDViODZhYzkxYThmMWMxZDgwZjZmYWM2YzE2ZTBjZGVmMDEzN2QyMDYyOTViYjc1NTU2MzJmZjMiLCJpYXQiOjE1NzM1NzUyNzIsIm5iZiI6MTU3MzU3NTI3MiwiZXhwIjoxNjA1MTk3NjcyLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.iy5FM6azkbf_UCIrtdnFFo0YjwXOserxhPV8okPRPHBMokRN9WoeffAXjoSVzhbZ5XWSNofqP8wa-w-9kSJTIO7AxfAnX7VPCfQxnFu8R7rrCRG42fI-uf7u6IL59J06s2WKH3Nlkji1muabC7NC2Y7652MsIy_8z_dcpVbmDu1mC_X3SyPT7im8ziYP9kJLKW-Cyj47DY-aq1LgqL9PcH08xTxMWAxGSavzFBQnLFg5nyxFP_L-8XVRZs3ZyxxId0xUUJFADjEH_6dD-czsJ3frZmVeaIhEkLg8K7zLaYaBGyvz9-81sxdxj2c-yYHzTIQ2f-QDAH9K-RggxiXZrVODJNY3tKQzxLLJE0X00fVcomQK0CcyerhwJ810_5Z36IbxYTn8NPUDvmHUo7cURb7xJSqogt3kl9Zn86PlG-5M0YQA_IFPIjR0RW4bIdY6YH4XGw8TYjy9-ARQmdCTScauTM2Cb9UT1K2dHIfzn05L7WTXaxfA57iGzt00IQqTz7rHPFURCtE-rw3eCHOW2CHjTab9ZrxyYz0ANKX3iCt0l9X96KIk7Q26AIjQiMIGySMZC927wbMKKU7igOYhimMFCsOgwRxgZC3j3hADvzqb4cXPNMIbmvpR_2z5MlDlF7m8dCx17T-6ka7mU_Gnlg_WH8Pka0LpvVYNHaJ0DnY

{
    "author_id": "2"
}

###
// GET/ bestAuthors REST (Getting Best Authors) 

POST  http://meditationv1.improsyazilim.com/public/api/bestAuthors HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzViMzE0MTYyM2EyZjI0NTFmNzk5OGM5YzZmYTgwNWQyY2UzMTRhYTEwNWFmY2Q5YmZiZDllYmQyMGU4MjViMzU5ZjdmNjY0MmY1OGVkNzciLCJpYXQiOjE1NzM2MzM3OTEsIm5iZiI6MTU3MzYzMzc5MSwiZXhwIjoxNjA1MjU2MTkxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.gYUOB1DZuJHKOpfpuQ19jOK7fSMJTlSQHO0Z-C-PIEXbOeeFfOEcEorZF_VUiWSQPAufGH0vPV6qBd99GIV0C4yIfwsoVpylypXrruyZzhVltrvVFq6vaUNvXxIs_aEFEXnkpUqBEEJ9y8xPzfpkyJTc0NLNpmy7SnIhMY1W1bFMHH_P4Q_Fk7tlsD04lxnK46QyKX-jPrgTrw0SrCbQLIv61SC_tHX9LSQiqdjDIT9GMGkKYU3WM0a1zB9I1S82X6unLwbcB_rHWLNfwFwrwTgYJ0sXN7A2yclXP8D1TMUjY_5j3vSKF9JojyfEdSb52HRQl0ZXEglOQIa117O49GJZVnOxkcJTBPRfVeGi2UxbUBM01kjo8WnuZFWcrp63UIGlFMtcXHvafpzcXpFtUA8K_ujE_Y3Ld0ofYF0-evaofuX8Eh9Oi64qfZ9X5kcd1MCiayyoHxWNSHRHxI6Hhc10owhpyTTYn-M8tBzVgSyk9chKgCX_FBBVL0A8s1h1tH1Ec4qddTq-AOdLgIebMlPq9BD4EA17Qr8UYX417xvC-rWwoIbRwKo6xpgMgIl6ghAbGfLQxmmgByWPoWvDUIVaY41mVvynkqZbYyiEBHpqpYGd8wf6BunOko3AXhZ2f7KdtVRvd9zGO65Tukd0cb_h_tkzwhsJNNaL8XB-68o
