###
//followers REST (Getting Auth User Followers) 

POST  http://meditationv1.improsyazilim.com/public/api/followers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDI4NTk0ZTkyYWQ2NWNmODZiMzU4YjlhYzZlMjY2MzY1ODI0M2NiMDNkNmI0YzllZjY3ZmE2MTE2ZTdmNTUwYjhmZDdmZTBlZWQ5NDhkY2UiLCJpYXQiOjE1NzM1NzM2NDgsIm5iZiI6MTU3MzU3MzY0OCwiZXhwIjoxNjA1MTk2MDQ4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.rGjE11BV2d8kggbLS1b609Dw5Zpxsm_zyl8wStfCIiduf6124WNRAz1hBLkPp2_L1T33q0lDfMI-YuuC1Omvi6hSmgl9vH3i26d0utZpPbz4OkOGXTw1c3QRZeNbdYMGrhwnyl6wSk83S1FLQDD0U7C3DNnWMZXn7DVbhE6ImgCgyrkiHfaFx9kPydDNWQ_MVE4mK4MlKpoRZy1x62nqpl3ZA6PKaMOvKsscKp6zKHMLRHf87uRagdQU8W_o0JYYM3OmSLKzCHip6yW8UD0BTL9cN10qs6DwuNHPeepdcR5sl2zMjQ7whGaqMqYmLhG-5D8Yt8Ttj2UzL95zc2J8UnLlNd7VM_ae-AWibXctk1nb_Z4jLKGqLekWLcl2_V7tNL0MERmiJx_CG0VzwBFuyzKAMnf-V2_244qiFjoXZ15PzPs7TgTHT3XqmQpOvUfKGD7mdSHODVzSbCq4PlWMOjvVctZxD2sEy3SC0Xji1Owl06yqW-gcNB0LBRaeInzZSBUgJlHyrdTO1bM9eE8crLBT2p_qP0wZw6yICp4laPX1QXHN115hdvdw9a8J_5rB7kAz_iWr_d-Ept7_NSp-05-u-UgoqDiT9nfqX6fYTFMiSMe2SnTka7yo-39U8ImlXBgCpKzysJ8cDdcITRl5yKGk9vkLzFXITLYochrzgMg

###
//followeds REST (Getting Auth User Followeds) 

POST  http://meditationv1.improsyazilim.com/public/api/followeds HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDI4NTk0ZTkyYWQ2NWNmODZiMzU4YjlhYzZlMjY2MzY1ODI0M2NiMDNkNmI0YzllZjY3ZmE2MTE2ZTdmNTUwYjhmZDdmZTBlZWQ5NDhkY2UiLCJpYXQiOjE1NzM1NzM2NDgsIm5iZiI6MTU3MzU3MzY0OCwiZXhwIjoxNjA1MTk2MDQ4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.rGjE11BV2d8kggbLS1b609Dw5Zpxsm_zyl8wStfCIiduf6124WNRAz1hBLkPp2_L1T33q0lDfMI-YuuC1Omvi6hSmgl9vH3i26d0utZpPbz4OkOGXTw1c3QRZeNbdYMGrhwnyl6wSk83S1FLQDD0U7C3DNnWMZXn7DVbhE6ImgCgyrkiHfaFx9kPydDNWQ_MVE4mK4MlKpoRZy1x62nqpl3ZA6PKaMOvKsscKp6zKHMLRHf87uRagdQU8W_o0JYYM3OmSLKzCHip6yW8UD0BTL9cN10qs6DwuNHPeepdcR5sl2zMjQ7whGaqMqYmLhG-5D8Yt8Ttj2UzL95zc2J8UnLlNd7VM_ae-AWibXctk1nb_Z4jLKGqLekWLcl2_V7tNL0MERmiJx_CG0VzwBFuyzKAMnf-V2_244qiFjoXZ15PzPs7TgTHT3XqmQpOvUfKGD7mdSHODVzSbCq4PlWMOjvVctZxD2sEy3SC0Xji1Owl06yqW-gcNB0LBRaeInzZSBUgJlHyrdTO1bM9eE8crLBT2p_qP0wZw6yICp4laPX1QXHN115hdvdw9a8J_5rB7kAz_iWr_d-Ept7_NSp-05-u-UgoqDiT9nfqX6fYTFMiSMe2SnTka7yo-39U8ImlXBgCpKzysJ8cDdcITRl5yKGk9vkLzFXITLYochrzgMg

###
//addFollower REST (Adding Follower) 

POST  http://meditationv1.improsyazilim.com/public/api/addFollower HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDI4NTk0ZTkyYWQ2NWNmODZiMzU4YjlhYzZlMjY2MzY1ODI0M2NiMDNkNmI0YzllZjY3ZmE2MTE2ZTdmNTUwYjhmZDdmZTBlZWQ5NDhkY2UiLCJpYXQiOjE1NzM1NzM2NDgsIm5iZiI6MTU3MzU3MzY0OCwiZXhwIjoxNjA1MTk2MDQ4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.rGjE11BV2d8kggbLS1b609Dw5Zpxsm_zyl8wStfCIiduf6124WNRAz1hBLkPp2_L1T33q0lDfMI-YuuC1Omvi6hSmgl9vH3i26d0utZpPbz4OkOGXTw1c3QRZeNbdYMGrhwnyl6wSk83S1FLQDD0U7C3DNnWMZXn7DVbhE6ImgCgyrkiHfaFx9kPydDNWQ_MVE4mK4MlKpoRZy1x62nqpl3ZA6PKaMOvKsscKp6zKHMLRHf87uRagdQU8W_o0JYYM3OmSLKzCHip6yW8UD0BTL9cN10qs6DwuNHPeepdcR5sl2zMjQ7whGaqMqYmLhG-5D8Yt8Ttj2UzL95zc2J8UnLlNd7VM_ae-AWibXctk1nb_Z4jLKGqLekWLcl2_V7tNL0MERmiJx_CG0VzwBFuyzKAMnf-V2_244qiFjoXZ15PzPs7TgTHT3XqmQpOvUfKGD7mdSHODVzSbCq4PlWMOjvVctZxD2sEy3SC0Xji1Owl06yqW-gcNB0LBRaeInzZSBUgJlHyrdTO1bM9eE8crLBT2p_qP0wZw6yICp4laPX1QXHN115hdvdw9a8J_5rB7kAz_iWr_d-Ept7_NSp-05-u-UgoqDiT9nfqX6fYTFMiSMe2SnTka7yo-39U8ImlXBgCpKzysJ8cDdcITRl5yKGk9vkLzFXITLYochrzgMg

{
    "followed_id": "2"
}