###
//lessons REST (Getting Auth User Lessons) 

POST  http://meditationv1.improsyazilim.com/public/api/lessons HTTP/1.1
content-type: application/json
Authorization: Bearer yJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNmQ4YzU5MGJkM2VlNjkyMTA3ZTM2ODlmMjAzMzliYTAwNzU0NTc1ODIzOTkxOWE3Yjk3NjA4MzU3YmI4NTQxYjkyMGYyZmFhM2FkNzRhZTciLCJpYXQiOjE1NzM1NzEyOTIsIm5iZiI6MTU3MzU3MTI5MiwiZXhwIjoxNjA1MTkzNjkyLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.HPmjHXeFdsv-fNEnzJq0-akNg0SAQByGZ1dXFPs53iVqmSQgXA8WEzqhvmtaQP34XHH_Fp0dZXRjZ2paLGrDpNU2u0c4cKQS_fi98UUhyPxmjdacjc6ultQAWjNNaoUw6c7QYRX678T8-kKcaimVWrl-9sKNbKhQLVeuzcK1scnJBu9c8Iuy-ztI8hHDZl8EOaDz5wYTpVG2j4hOxygH1MrRnGTWsBI7_BFSnSztjxn6HaebXo3gDyn1c0oZ27H0c6bF00du86nK8QLkBV6Vu1wu8fZmrYGzT6LeyMjeYsf1jtC_f_A54pmTYGGvMCBMoPLsF_7VJ9_lMmSbQ8hQ1SmkCahKeDswmv-BuKSkXEwmIY0PpjSSNQNoHG-S65xJP94oBa9f5Ep7job-_YSXzZ2YAG8zsluf2GZMDzXcdjNOu_1ZAnw6GpLY2i8oQnBLZ8v3Nnxa9q8J2Sz2u1crBTzrPUfpB3p-dwQ5c2ssPJX5UkrWv6ojdzsA5Aggb5maRSzpim0hQHuEhLD1XNPqMUsBfnVjqaFrKsgiY1tp-76jnbCZzWHYXJ0vZx2W3V3k5WB5D4hbM3RQw9UZuy-gea87wQlKOlbZXxvfe6u9wO0qecXXFSVFHHm8tQZbBfGe5J1-mGF_ztYQUqRAyghz1CWMJMqbRMP1yMbb1UdnxYg

###
//backgroundLessons REST (Getting All Background Lessons) 

POST  http://meditationv1.improsyazilim.com/public/api/backgroundLessons HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODFjNTc1ZWUwMWM5ZTc5Njg0YmQxNDExMjI5M2IxODI3NzMxNWE4M2RjOTA2ODdjMDQ0NDY4YThhYjA1YzgyMmU2YzE1YjEzYzhmYzFiNTEiLCJpYXQiOjE1NzM1NzQwMTgsIm5iZiI6MTU3MzU3NDAxOCwiZXhwIjoxNjA1MTk2NDE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.rrMC1_CYAJC90lpt-B81CcLCNhNCkkj_pTLcVYUo9ZfWZaj7GhibSmYS9t71YFaAORU_0GALcm1ixSRMcUeNWP5e0PEaNu9widwrzHi2CEo5FEtnZ3r5fLNOHgzPkzeuOEgEQBL6NNVQregUhhk4j_3mv_tLsA8Jeq_LIBQedb5OifR9vflRffO-bnfFkRGR6Bv6u5LWGwfAvcXOWyMcJOn7Xc4EWnbs7v9Q_Mr8vRlTpnsoHpxgx6YhN03OBHn3ZEbFGl1jEvwr3rQYh4oGyHofw9vHSGiz1-usfYW42nKnzvSOKtFT1qpkXxktvgLHd6FHcwLjX_djqWrpsM7TTqZKzNmhVlygZHc0w6_KNUQNDuqPi3sL84zEkxrht4fKd22GinZUFa05BbuTHqwlgPqk7wKymgx8MeZD3DZ7zIxpnbICSnirTjc8vrwcV35Zj9wIssL3eyElHAMsMTH7ofH0ldTr5MIdcRB6FtcYyEqax4WaOZ9LiXzRM_aHpTMC7NquJNmzzybvaR0MlByvVV-r5lnWIv1vbbCpm2tM9b3fkNy34fq6r-ay_zOXlVErG5a4lSqqDeYGatf-J3I7UNpjGn2vCEq4bEfLGHjjF10MTjM7T5XbGy82wQgcqbtbwh_KmK_dNQlxds1kdGK4Gf5n_Yh478euCDdYeDKA6YQ

###
//lastLessons REST (Getting Last Inserted Lessons) 

POST  http://meditationv1.improsyazilim.com/public/api/lastLessons HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDdhM2EzOTUxOTRjZDM5OTFmZTI5ODRmZjM3ZmVjYWMzMTg0NGY0MTY5Zjg5NDI1ZjY2ZDE1MzViMjk4Zjk1YzFiMWUwYzQ3Y2E5OTJjNjAiLCJpYXQiOjE1NzM2NDI2NzksIm5iZiI6MTU3MzY0MjY3OSwiZXhwIjoxNjA1MjY1MDc5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.bAIEgyihAhcT-xKv-hW44a6lmmMHyiKME-3V7WpdQHCvFyBLHHiYmumLK2whqV9wga7xq90R-wiEcc8Oi032p8KAIuTND_ZGQGixfLwlQlb_wYKWEZACyMSOfYVh4ZEZVE81Q48QwqMdf5A9iSv9S_VL__1TM060VL8GfKoN0xp7qK1MwHU-sMh0yRIBEm3eG6OLgZ0yigzfxuncAEPt9HlKozutsCVOaHeUh7Ocd-5Jd-twwpN07QxvKpUnNvxP4NMZz7DHa-_p0e22z2Su8uRivyThWRMcNQcBz_UP1TvkBNw3fh0JdfXe9bwZ3VTGqIQxl32LMoD3KZ0ukY5gmt4v1FwMvXymJu2kk7uJVKWV7bgaNcUDvT4_QmZnbisdu7p7xgTIxfbEW1h1IhVrs8EaD8CK7ifthyoJmBlbGGAJ8NsXB0oH7OcjjePgYPRKhDI4GmrASk7dW3vV_OISjcVtgNm0_FCfzTl_Jzr_AtUbXJ_fccHeA1Leg2Hb6-MKHI0I398LgktaA-cxnh5QBMsgp2PK0ZfmiOxQWRpCI1seEejldzqk2U83vB-tMUabGkTu-9zIdzrJmgRy_5BT9rwgoqclnR2arlqgKTN5Z98ijQCZLfHNnnuNP2Gc9BYQDfbAoCE396x3geRBu0Kvn-bDKRJwaRrvAuVLtFwJqg8

###
// GET/ topLessonsWeekly REST (Getting Top Lessons Weekly) 

POST  http://meditationv1.improsyazilim.com/public/api/topLessonsWeekly HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzViMzE0MTYyM2EyZjI0NTFmNzk5OGM5YzZmYTgwNWQyY2UzMTRhYTEwNWFmY2Q5YmZiZDllYmQyMGU4MjViMzU5ZjdmNjY0MmY1OGVkNzciLCJpYXQiOjE1NzM2MzM3OTEsIm5iZiI6MTU3MzYzMzc5MSwiZXhwIjoxNjA1MjU2MTkxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.gYUOB1DZuJHKOpfpuQ19jOK7fSMJTlSQHO0Z-C-PIEXbOeeFfOEcEorZF_VUiWSQPAufGH0vPV6qBd99GIV0C4yIfwsoVpylypXrruyZzhVltrvVFq6vaUNvXxIs_aEFEXnkpUqBEEJ9y8xPzfpkyJTc0NLNpmy7SnIhMY1W1bFMHH_P4Q_Fk7tlsD04lxnK46QyKX-jPrgTrw0SrCbQLIv61SC_tHX9LSQiqdjDIT9GMGkKYU3WM0a1zB9I1S82X6unLwbcB_rHWLNfwFwrwTgYJ0sXN7A2yclXP8D1TMUjY_5j3vSKF9JojyfEdSb52HRQl0ZXEglOQIa117O49GJZVnOxkcJTBPRfVeGi2UxbUBM01kjo8WnuZFWcrp63UIGlFMtcXHvafpzcXpFtUA8K_ujE_Y3Ld0ofYF0-evaofuX8Eh9Oi64qfZ9X5kcd1MCiayyoHxWNSHRHxI6Hhc10owhpyTTYn-M8tBzVgSyk9chKgCX_FBBVL0A8s1h1tH1Ec4qddTq-AOdLgIebMlPq9BD4EA17Qr8UYX417xvC-rWwoIbRwKo6xpgMgIl6ghAbGfLQxmmgByWPoWvDUIVaY41mVvynkqZbYyiEBHpqpYGd8wf6BunOko3AXhZ2f7KdtVRvd9zGO65Tukd0cb_h_tkzwhsJNNaL8XB-68o

