###
//search (Searching Sentence in Category,Author,Sound,Lesson) 

POST  http://meditationv1.improsyazilim.com/public/api/search HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTZhODI1ODcwYjE3M2UxNjRjNWYzY2Q0NWVkYzZiNzAzNTk3NDNhYmE0ZjA3ZGFiMjFjY2IyNzI0MjRjMmIzNmEyOGNhNGQ1YzNhMWVhNWMiLCJpYXQiOjE1NzM1Nzc0MTcsIm5iZiI6MTU3MzU3NzQxNywiZXhwIjoxNjA1MTk5ODE3LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.fAk6ExxOxIYUJxq7iDDA8g3qbH_1kjW5Qe6iQYNum3CQaYz2VPcwvvkZEONy-_ZHnSVdfjV-h_lm1haFU6GyE1xwgU4QeO4RUefcDjZ-t6ynWGeHcgb1kDShB1fgkvS8T0axvK-PdUc-81mcNT2RF54HxHdPdHUd5Myd-mWvwZ24p4fDwrmOX93-VJ3ai69K_i6w2KtBSx5iS3_Gru-SWZ-CAwU1wWJEQj4rjcBfSFgQFNU3fYfSdesrL3RVurkTqcWvdLgAE19zT2tZ6f8PdnfbJ4vtZrL8tyB1RmV4yo6Gm3K-RVDtPgb4XaoOa1SK4UzfrVCeq51dbYchPwW8LzZZzal9C71Um2xYVFq4fhANBM5L1_plaThmFBNoBiNqKK2QM5tLFmiSQdmiHeenNzsa2kTdDaGt4lMFJvsfuhj1Ci08ewUxsgHLtLcC6X5a_O59wPD8hK6K-Ve6kfOtrs2-xgVyZ2I5guB4IRWt-cMOipHa7KVoxW5hD6XKnEfSSlY-10eQH_Tdn5vTxxtM5QWYU0TgLUy6A4gxsY9UQp7lbLcfmgNR-YS0viEG_UgI75qexemI4RQFw3d4hu42YYholL-h0Iv9_jCko7HwprjiLr-Pfv4cogjgWBm-IvUFQffBNALxcfQg74sopkAXDLSmUEgoWziGPdkW9beNXSM

{
    "sentence": "Test"
}