###
//tags REST (Getting All Tags) 

POST http://meditationv1.improsyazilim.com/public/api/tags HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWI4MGFmZmJjZGYxY2JkMzZhNjA3OTM4ZWYyNDExZDNmZTdjNjlhYjc0NTZmMDJkNzZlM2JlNDI3MzRmYWEzZGVlZTRmZWQ3ZDU5ZjY1ZjYiLCJpYXQiOjE1NzM1NjUwNjcsIm5iZiI6MTU3MzU2NTA2NywiZXhwIjoxNjA1MTg3NDY3LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.sgK-DEGRu-mHXVWLyFvUbu0FZG4_nDPnxXyC4BRf8X3lAdmaEUiPcE-1GPf5SaUShqtmHmkmQhiUOW1DMuf-jl_ny4zT4RRTdTIp7-VFUR3S9CUJ8ZWt55oi8g0vLd96NgpVHg5wFmiGKAW1VxMzW2m81UchGsx7SMijebAsjhzadYzeMMpdzBsi57g7nMtF5ObC-2FNuSCRfq538phyUeLaweJrEgaDDeh4hLZt4ps3N1uXNWC_YWMyVEP95yfeiImjJjN1L4i9xYYjKvJuD0L5xy5D18u_ECPrU9VCtUBK5rs9YUcgtjCmwGQ3hUlWuDTtPxH3odmzrWdyMYnTg7tqpSERDC7pWsWTL8bUYOi4zL38_3PT6zPnnraruQkOlFqmrCeGHLNPGv1WDTyB31bm84nOWuq1UdxN-sbtUhFHxL72UvpoJ260jYL3JIguZwbIgtonrqapAmD4qKThC4113XwQn_BiP40zRK98mP_xZdd1OHbGkTDCWcykL7lGrE9Jp3oBe-45vGJRgi_b9Ga75bIRPXdXyk808kZRaPNXevEtWdH9PvlcAV7xjU8-ZNCvUA6LiTN34y1pc57HwWDnPyLnENQ2ChdlZiM_FJE8JbW9EkrzVgcGSN1A6teSvt5oxy66mxnUIGNEMUOrVuzP_pfBVpi1QNYCJTISQPw

###
//addTag REST (Adding Tags) 

POST http://meditationv1.improsyazilim.com/public/api/addTag HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWI4MGFmZmJjZGYxY2JkMzZhNjA3OTM4ZWYyNDExZDNmZTdjNjlhYjc0NTZmMDJkNzZlM2JlNDI3MzRmYWEzZGVlZTRmZWQ3ZDU5ZjY1ZjYiLCJpYXQiOjE1NzM1NjUwNjcsIm5iZiI6MTU3MzU2NTA2NywiZXhwIjoxNjA1MTg3NDY3LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.sgK-DEGRu-mHXVWLyFvUbu0FZG4_nDPnxXyC4BRf8X3lAdmaEUiPcE-1GPf5SaUShqtmHmkmQhiUOW1DMuf-jl_ny4zT4RRTdTIp7-VFUR3S9CUJ8ZWt55oi8g0vLd96NgpVHg5wFmiGKAW1VxMzW2m81UchGsx7SMijebAsjhzadYzeMMpdzBsi57g7nMtF5ObC-2FNuSCRfq538phyUeLaweJrEgaDDeh4hLZt4ps3N1uXNWC_YWMyVEP95yfeiImjJjN1L4i9xYYjKvJuD0L5xy5D18u_ECPrU9VCtUBK5rs9YUcgtjCmwGQ3hUlWuDTtPxH3odmzrWdyMYnTg7tqpSERDC7pWsWTL8bUYOi4zL38_3PT6zPnnraruQkOlFqmrCeGHLNPGv1WDTyB31bm84nOWuq1UdxN-sbtUhFHxL72UvpoJ260jYL3JIguZwbIgtonrqapAmD4qKThC4113XwQn_BiP40zRK98mP_xZdd1OHbGkTDCWcykL7lGrE9Jp3oBe-45vGJRgi_b9Ga75bIRPXdXyk808kZRaPNXevEtWdH9PvlcAV7xjU8-ZNCvUA6LiTN34y1pc57HwWDnPyLnENQ2ChdlZiM_FJE8JbW9EkrzVgcGSN1A6teSvt5oxy66mxnUIGNEMUOrVuzP_pfBVpi1QNYCJTISQPw

{
    "name": "Test Tag Name"
}

###
//hashTags REST (Adding Tags) 

POST  http://meditationv1.improsyazilim.com/public/api/hashTags HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWI4MGFmZmJjZGYxY2JkMzZhNjA3OTM4ZWYyNDExZDNmZTdjNjlhYjc0NTZmMDJkNzZlM2JlNDI3MzRmYWEzZGVlZTRmZWQ3ZDU5ZjY1ZjYiLCJpYXQiOjE1NzM1NjUwNjcsIm5iZiI6MTU3MzU2NTA2NywiZXhwIjoxNjA1MTg3NDY3LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.sgK-DEGRu-mHXVWLyFvUbu0FZG4_nDPnxXyC4BRf8X3lAdmaEUiPcE-1GPf5SaUShqtmHmkmQhiUOW1DMuf-jl_ny4zT4RRTdTIp7-VFUR3S9CUJ8ZWt55oi8g0vLd96NgpVHg5wFmiGKAW1VxMzW2m81UchGsx7SMijebAsjhzadYzeMMpdzBsi57g7nMtF5ObC-2FNuSCRfq538phyUeLaweJrEgaDDeh4hLZt4ps3N1uXNWC_YWMyVEP95yfeiImjJjN1L4i9xYYjKvJuD0L5xy5D18u_ECPrU9VCtUBK5rs9YUcgtjCmwGQ3hUlWuDTtPxH3odmzrWdyMYnTg7tqpSERDC7pWsWTL8bUYOi4zL38_3PT6zPnnraruQkOlFqmrCeGHLNPGv1WDTyB31bm84nOWuq1UdxN-sbtUhFHxL72UvpoJ260jYL3JIguZwbIgtonrqapAmD4qKThC4113XwQn_BiP40zRK98mP_xZdd1OHbGkTDCWcykL7lGrE9Jp3oBe-45vGJRgi_b9Ga75bIRPXdXyk808kZRaPNXevEtWdH9PvlcAV7xjU8-ZNCvUA6LiTN34y1pc57HwWDnPyLnENQ2ChdlZiM_FJE8JbW9EkrzVgcGSN1A6teSvt5oxy66mxnUIGNEMUOrVuzP_pfBVpi1QNYCJTISQPw



###
//addHashTag REST (Adding Tags) 

POST  http://meditationv1.improsyazilim.com/public/api/addHashTag HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWI4MGFmZmJjZGYxY2JkMzZhNjA3OTM4ZWYyNDExZDNmZTdjNjlhYjc0NTZmMDJkNzZlM2JlNDI3MzRmYWEzZGVlZTRmZWQ3ZDU5ZjY1ZjYiLCJpYXQiOjE1NzM1NjUwNjcsIm5iZiI6MTU3MzU2NTA2NywiZXhwIjoxNjA1MTg3NDY3LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.sgK-DEGRu-mHXVWLyFvUbu0FZG4_nDPnxXyC4BRf8X3lAdmaEUiPcE-1GPf5SaUShqtmHmkmQhiUOW1DMuf-jl_ny4zT4RRTdTIp7-VFUR3S9CUJ8ZWt55oi8g0vLd96NgpVHg5wFmiGKAW1VxMzW2m81UchGsx7SMijebAsjhzadYzeMMpdzBsi57g7nMtF5ObC-2FNuSCRfq538phyUeLaweJrEgaDDeh4hLZt4ps3N1uXNWC_YWMyVEP95yfeiImjJjN1L4i9xYYjKvJuD0L5xy5D18u_ECPrU9VCtUBK5rs9YUcgtjCmwGQ3hUlWuDTtPxH3odmzrWdyMYnTg7tqpSERDC7pWsWTL8bUYOi4zL38_3PT6zPnnraruQkOlFqmrCeGHLNPGv1WDTyB31bm84nOWuq1UdxN-sbtUhFHxL72UvpoJ260jYL3JIguZwbIgtonrqapAmD4qKThC4113XwQn_BiP40zRK98mP_xZdd1OHbGkTDCWcykL7lGrE9Jp3oBe-45vGJRgi_b9Ga75bIRPXdXyk808kZRaPNXevEtWdH9PvlcAV7xjU8-ZNCvUA6LiTN34y1pc57HwWDnPyLnENQ2ChdlZiM_FJE8JbW9EkrzVgcGSN1A6teSvt5oxy66mxnUIGNEMUOrVuzP_pfBVpi1QNYCJTISQPw

{
    "name": "Test Hash Tag Name"
}